### PR TITLE
🚩: Milestone: "Hello world" one app with Webpack

### PR DESCRIPTION
**Pull request by Ruthmy**
## 🚩: Milestone: "Hello world" one app with Webpack <a name="milestone-1"></a>

Hi there! @Ruthmy here.

This is the first milestone of the "Hello world" one app with Webpack project. The goal of this milestone is to build a simple "Hello world" app using Webpack and display a greeting message anytime the user reloads the page.

### Here is a summary of what has been done:

- [x] Create a new Rails app with Webpack, React and Redux.
- [x] Set PostgreSQL as the database.
- [x] Create an API endpoint to serve the greeting message.
- [x] Create an App component to render the static content.
- [x] Create a Greeting component to render the greeting message.
- [x] Create a store, an action and a reducer to fetch the greeting message from the API endpoint.

---

### Thank you for taking the time to review this PR ⭐!

---

### CODE REVIEW

**Review by Shedrack-Sunday — CHANGES_REQUESTED** [review]
Hi @Ruthmy  

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

# Invalid Code Review Request 🔴 

You have submitted a project, that does not have a link to your backend PR. Kindly add the link to your README  while making sure the README  is also solid 

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

**Comment by Ruthmy** [comment]
Hi  @Shedrack-Sunday Thanks for your feedback.
I think maybe there is some confusion. This exercise does not require two parts. Only one app with rails and react.
The exercise that takes two PRs together, is the [Set up a "Hello world" project with two apps](https://github.com/microverseinc/curriculum-rails/blob/main/connect-frontend-frameworks/hello_world_two_apps.md#set-up-a-hello-world-project-with-two-apps) and I am not doing that one yet.
This is [Set up a "Hello world" project as one app with Webpack](https://github.com/microverseinc/curriculum-rails/blob/main/connect-frontend-frameworks/rails_react_webpack.md#set-up-a-hello-world-project-as-one-app-with-webpack)

**Comment by Shedrack-Sunday** [comment]
Hello @Ruthmy , You are right. However, it seems you submitted the PR on the review slot of the two apps requirement. I will go on to review it shortly since its the right one this time.

**Review by Shedrack-Sunday — APPROVED** [review]
Hi @Ruthmy    

Your project is complete! There is nothing else to say other than... it's time to merge it :shipit:
Congratulations! 🎉

image


Highlights
- [x] Good project organization ✔️
- [x] Nice use of Rails features ✔️ 
- [x] Beautiful use of webpack 💯 
- [x] Kudus on meeting the requirements   👏 

### Confirmed view:
image


Optional suggestions
Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application.


Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s).

**Pull request merged**
